name: telepathy
description: the AI chat hub
version: 0.0.1
environment:
  sdk: ">=2.14.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  wheel:
    git:
      url: https://github.com/RedDwarfTech/wheel.git
      ref: main

